### ISSUE TITLE
Files are not available

### ISSUE THREAD

**Issue by Hamid-Nasiri** [Saakaarb/Deep-Learning-for-Aerodynamic-Prediction#2]
Currently the mat files that you uploaded on Google Drive are not available. Would you please kindly send me the following .mat files?

Output_rho.mat
Output_u.mat
Output_v.mat
Output_p.mat

SDF_values.mat
Input_re_alpha.mat

My email address:
h.nasiri@aut.ac.ir

**Comment by preeyshah** [comment]
Even I am not able to access the data files. Could you share them with the following email address: preey@stanford.edu
Any help will be appreciated.

Thanks,
Preey

**Comment by Parimal60** [comment]
Data is not accessible.  Can you please share them with following address: parimalg@iisc.ac.in 

Thanks, 
Parimal

**Comment by PrathamLearnsToCode** [comment]
Hi, the files are not available. Please share them at prathamgrover_bt20a3_13@dtu.ac.in. Thanks.

Regards,
Pratham

**Comment by zhangzhang2222** [comment]
Data is not accessible. Can you please share them with following address: agnes_xuexi@outlook.com
Thanks,

**Comment by 1smile1234** [comment]
Hello, can you send the data to my email at miaomiao_sun@163.com? thank you.

**Comment by KingVandal** [comment]
Hello,MAT data is not available .Please share them at arali856@gmail.com .Thanks.

**Comment by KingVandal** [comment]
HI. can u send the data to my email at arali856@gmail.com  . tanks.

**Comment by failedpupil** [comment]
can u send data files to hntejas002@gmail.com

**Comment by Saakaarb** [comment]
Apologies for the broken data links and the delay in response, the repo has not been updated/maintained for a long time. The links have been fixed. Thank you
